name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.11.0", "<2.0.0"]

seeds: 
  +docs:
    node_color: '#cd7f32'

models:
  jaffle_shop:
    +materialized: table
    +meta:
      metadata_checks:
        require_model_description: true
        require_column_descriptions: false
        require_primary_key_test: false
        require_indexed_columns: true
        single_column_unique_requires_not_null: true
        primary_key_tests:
          - unique
          - dbt_utils.unique_combination_of_columns
          - dbt_expectations.expect_compound_columns_to_be_unique
    staging:
      +materialized: view
      +meta:
        metadata_checks:
          require_column_descriptions: true
          require_primary_key_test: true
      +docs:
        node_color: 'silver'
    +docs:
      node_color: 'gold'
